routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home.index');

Route::group(['middleware' => ['web', 'guest']], function () {
    Route::get('/masuk', 'AuthController@index')->name('masuk');
    Route::post('/masuk', 'AuthController@masuk');
});

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::post('/keluar', 'AuthController@keluar')->name('keluar');

    Route::get('/pengaturan', 'UserController@pengaturan')->name('pengaturan');
    Route::get('/profil', 'UserController@profil')->name('profil');
    Route::patch('/update-pengaturan/{user}', 'UserController@updatePengaturan')->name('update-pengaturan');
    Route::patch('/update-profil/{user}', 'UserController@updateProfil')->name('update-profil');

    Route::group(['middleware' => ['peran']], function () {
        Route::get('/identitas-desa', 'DesaController@index')->name('identitas-desa');
        Route::patch('/identitas-desa/update-desa/{desa}', 'DesaController@update')->name('update-desa');

        Route::get('/informasi', 'GalleryController@informasi')->name('informasi.index');

        Route::get('/pengaturan-surat', 'PengaturanSuratController@index')->name('pengaturan-surat.index');
        Route::post('/pengaturan-surat', 'PengaturanSuratController@update')->name('pengaturan-surat.update');

        Route::resource('dusun', 'DusunController')->except('show');
        Route::resource('/dusun/detailDusun', 'DetailDusunController')->except('create','edit');

        Route::post('user/reset-password/{user}', 'UserController@reset_password')->name('user.reset-password');
        Route::resource('user', 'UserController')->except('show');
    });
});

Route::get('/{any}', 'ArtikelController@show')->where('any', '.*')->name('artikel.show');

app/Dusun.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dusun extends Model
{
    protected $table = "dusun";
    protected $guarded = [];

    public function detailDusun()
    {
        return $this->hasMany('App\DetailDusun');
    }
}

app/Http/Controllers/DusunController.php
<?php

namespace App\Http\Controllers;

use App\Dusun;
use Illuminate\Http\Request;

class DusunController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dusun.index', ['dusun' => Dusun::latest()->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dusun.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'nama' => ['required','string','max:50']
        ]);

        $dusun = Dusun::create($data);
        return redirect()->route('dusun.edit',$dusun)->with('success','Dusun berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dusun  $dusun
     * @return \Illuminate\Http\Response
     */
    public function show(Dusun $dusun)
    {
        return view('dusun.show', compact('dusun'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dusun  $dusun
     * @return \Illuminate\Http\Response
     */
    public function edit(Dusun $dusun)
    {
        return view('dusun.edit', compact('dusun'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dusun  $dusun
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dusun $dusun)
    {
        $data = $request->validate([
            'nama' => ['required','string','max:50']
        ]);

        $dusun->update($data);
        return redirect()->back()->with('success','Dusun berhasil diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dusun  $dusun
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dusun $dusun)
    {
        $dusun->delete();
        return redirect()->route('dusun.index')->with('success','Dusun berhasil dihapus');
    }
}

resources/views/dusun/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Dusun')

@section('content-header')
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-image: url({{ asset('/img/cover-bg-profil.jpg') }}); background-size: cover; background-position: center top;">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card shadow h-100">
                    <div class="card-header border-0">
                        <div class="d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-md-between text-center text-md-left">
                            <div class="mb-3">
                                <h2 class="mb-0">Tambah Dusun</h2>
                                <p class="mb-0 text-sm">Kelola Dusun</p>
                            </div>
                            <div class="mb-3">
                                <a href="{{ route("dusun.index") }}" class="btn btn-success" title="Kembali"><i class="fas fa-arrow-left"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
@include('layouts.components.alert')
<div class="row">
    <div class="col-md-5">
        <div class="card bg-secondary shadow h-100">
            <div class="card-body">
                <form autocomplete="off" action="{{ route('dusun.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label class="form-control-label" for="nama">Nama Dusun</label>
                        <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" placeholder="Masukkan Nama Dusun ..." value="{{ old('nama') }}">
                        @error('nama')<span class="invalid-feedback font-weight-bold">{{ $message }}</span>@enderror
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" id="simpan">SIMPAN</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dusun/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Dusun')

@section('content-header')
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-image: url({{ asset('/img/cover-bg-profil.jpg') }}); background-size: cover; background-position: center top;">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-md-between text-center text-md-left">
                            <div class="mb-3">
                                <h2 class="mb-0">Edit Dusun</h2>
                                <p class="mb-0 text-sm">Kelola Dusun</p>
                            </div>
                            <div class="mb-3">
                                <a href="{{ route("dusun.index") }}" class="btn btn-success" title="Kembali"><i class="fas fa-arrow-left"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('content')
@include('layouts.components.alert')
<div class="row">
    <div class="col-md-5 mb-3">
        <div class="card bg-secondary shadow">
            <div class="card-body">
                <form autocomplete="off" action="{{ route('dusun.update', $dusun) }}" method="post">
                    @csrf @method('patch')
                    <div class="form-group">
                        <label class="form-control-label" for="nama">Nama Dusun</label>
                        <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" placeholder="Masukkan Nama Dusun ..." value="{{ old('nama', $dusun->nama) }}">
                        @error('nama')<span class="invalid-feedback font-weight-bold">{{ $message }}</span>@enderror
                    </div>
                    <button type="submit" class="btn btn-primary btn-block" id="simpan">SIMPAN</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-7 mb-3">
        <div class="card bg-secondary shadow">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <h2 class="mb-0">Detail Dusun</h2>
                    <a href="#modal-tambah-detail-dusun" data-toggle="modal" class="btn btn-success btn-sm"><i class="fas fa-plus"></i> Tambah</a>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <th width="20px">#</th>
                            <th>RW</th>
                            <th>RT</th>
                            <th>Opsi</th>
                        </thead>
                        <tbody>
                            @forelse ($dusun->detailDusun as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->rw }}</td>
                                    <td>{{ $item->rt }}</td>
                                    <td>
                                        <a href="#modal-edit-detail-dusun" class="btn btn-sm btn-success edit" data-get="{{ route('detailDusun.show', $item) }}" data-action="{{ route('detailDusun.update', $item) }}" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                                        <a class="btn btn-sm btn-danger hapus-data" data-nama="RT/RW {{ $item->rt }}/{{ $item->rw }}" data-action="{{ route("detailDusun.destroy", $item) }}" data-toggle="tooltip" title="Hapus" href="#modal-hapus"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" align="center">Data tidak tersedia</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-hapus" tabindex="-1" role="dialog" aria-labelledby="modal-hapus" aria-hidden="true">
    <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
        <div class="modal-content bg-gradient-danger">

            <div class="modal-header">
                <h6 class="modal-title" id="modal-title-delete">Hapus Detail Dusun?</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">

                <div class="py-3 text-center">
                    <i class="ni ni-bell-55 ni-3x"></i>
                    <h4 class="heading mt-4">Perhatian!!</h4>
                    <p>Menghapus dusun akan menghapus semua data yang dimilikinya</p>
                    <p><strong id="nama-hapus"></strong></p>
                </div>

            </div>

            <div class="modal-footer">
                <form id="form-hapus" action="" method="POST" >
                    @csrf @method('delete')
                    <button type="submit" class="btn btn-white">Yakin</button>
                </form>
                <button type="button" class="btn btn-link text-white ml-auto" data-dismiss="modal">Tidak</button>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="modal-edit-detail-dusun" tabindex="-1" role="dialog" aria-labelledby="modal-edit-detail-dusun" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="modal-title">Edit Detail Dusun</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <form class="form form-edit" data-redirect="{{ route('dusun.edit',$dusun) }}" action="" method="POST">
                    @csrf @method('patch')
                    <input type="hidden" name="dusun_id" value="{{ $dusun->id }}">
                    <div class="form-group">
                        <label class="form-control-label">RW</label>
                        <input type="text" class="form-control" id="rw" name="rw" placeholder="Masukkan RW ...">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">RT</label>
                        <input type="text" class="form-control" id="rt" name="rt" placeholder="Masukkan RT ...">
                    </div>
                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-white" data-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-tambah-detail-dusun" tabindex="-1" role="dialog" aria-labelledby="modal-tambah-detail-dusun" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="modal-title">Tambah Detail Dusun</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <form class="form" data-redirect="{{ route('dusun.edit',$dusun) }}" action="{{ route("detailDusun.store") }}" method="POST">
                    @csrf
                    <input type="hidden" name="dusun_id" value="{{ $dusun->id }}">
                    <div class="form-group">
                        <label class="form-control-label">RW</label>
                        <input type="text" class="form-control" name="rw" placeholder="Masukkan RW ...">
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">RT</label>
                        <input type="text" class="form-control" name="rt" placeholder="Masukkan RT ...">
                    </div>
                    <div class="d-flex justify-content-between">
                        <button type="button" class="btn btn-white" data-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(document).on('click', '.edit', function (event) {
        event.preventDefault();
        const btn = this;
        $(".form-edit").attr('action', $(this).data('action'));
        $.ajax({
            url: $(this).data('get'),
            method: 'get',
            beforeSend: function (){
                $(btn).attr('disabled','disabled');
                $(btn).html(`<img height="20px" src="${baseURL}/storage/loading.gif" alt="">`);
            },
            success: function (response) {
                $(btn).html('<i class="fas fa-edit"></i>');
                $(btn).removeAttr('disabled');
                $("#modal-edit-detail-dusun").modal('show');
                $("#rw").val(response.rw);
                $("#rt").val(response.rt);
            }
        });
    });

    $(document).on('submit', '.form', function(event) {
        event.preventDefault();
        const form = this;
        const url = $(this).attr('action');
        const redirect = $(this).data('redirect');
        $.ajax({
            url: url,
            type: 'POST',
            data: new FormData(form),
            dataType: 'json',
            contentType: false,
            cache: false,
            processData: false,
            success: function(result){
                $(form).find("button:submit").html('Simpan');
                $(form).find("button:submit").removeAttr('disabled');
                if (result.success) {
                    alertSuccess(result.message);
                    setTimeout(() => {
                        $(".notifikasi").html('');
                    }, 3000);
                    if (redirect) {
                        location.href = redirect;
                    }
                }
            },
            error: function (response) {
                console.clear();
                $(form).find('button:submit').html('Simpan');
                $(form).find('button:submit').removeAttr('disabled');
                alertError();
                let focus = true;
                $.each(response.responseJSON.errors, function (i, e) {
                    $('#pesanError').append(`<li>`+e+`</li>`);
                    if (!$(form).find("[name='" + i + "']").hasClass('is-invalid')) {
                        $(form).find("[name='" + i + "']").addClass('is-invalid');
                        if (focus) {
                            $("[name='" + i + "']").focus();
                            focus = false;
                        }
                    }
                });
            }
        });
    });
</script>
@endpush

resources/views/dusun/index.blade.php
@extends('layouts.app')

@section('title', 'Wilayah Administratif')

@section('styles')
<link href="{{ asset('/css/style.css') }}" rel="stylesheet">
@endsection

@section('content-header')
<div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="background-image: url({{ asset('/img/cover-bg-profil.jpg') }}); background-size: cover; background-position: center top;">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="card shadow h-100">
                    <div class="card-header border-0">
                        <div class="d-flex flex-column flex-md-row align-items-center justify-content-center justify-content-md-between text-center text-md-left">
                            <div class="mb-3">
                                <h2 class="mb-0">Wilayah Administratif</h2>
                                <p class="mb-0 text-sm">Kelola Wilayah Administratif</p>
                            </div>
                            <div class="mb-3">
                                <a href="{{ route('dusun.create') }}" class="btn btn-success" title="Tambah"><i class="fas fa-plus"></i> Tambah Dusun</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('form-search')
<form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto" action="{{ URL::current() }}" method="GET">
    <div class="form-group mb-0">
        <div class="input-group input-group-alternative">
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Cari ...." type="search" name="cari" value="{{ request('cari') }}">
        </div>
    </div>
</form>
@endsection

@section('form-search-mobile')
<form class="mt-4 mb-3 d-md-none" action="{{ URL::current() }}" method="GET">
    <div class="input-group input-group-rounded input-group-merge">
        <input type="search" name="cari" class="form-control form-control-rounded form-control-prepended" placeholder="cari" aria-label="Search" value="{{ request('cari') }}">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <span class="fa fa-search"></span>
            </div>
        </div>
    </div>
</form>
@endsection

@section('content')
@include('layouts.components.alert')
<div class="card shadow">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover table-sm table-striped table-bordered">
                <thead>
                    <th class="text-center" width="20px">#</th>
                    <th class="text-center" width="100px">Opsi</th>
                    <th class="text-center">Nama Dusun</th>
                </thead>
                <tbody>
                    @forelse ($dusun as $item)
                        <tr>
                            <td style="vertical-align: middle">{{ $loop->iteration }}</td>
                            <td style="vertical-align: middle">
                                <a href="{{ route('dusun.edit', $item) }}" class="btn btn-sm btn-success" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                                <a class="btn btn-sm btn-danger hapus-data" data-nama="{{ $item->nama }}" data-action="{{ route("dusun.destroy", $item) }}" data-toggle="tooltip" title="Hapus" href="#modal-hapus"><i class="fas fa-trash"></i></a>
                            </td>
                            <td style="vertical-align: middle">{{ $item->nama }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="15" align="center">Data tidak tersedia</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

@include('layouts.components.hapus', ['nama_hapus' => 'dusun'])
@endsection